export const emotionToTrait = {
    "admiration": ["Agreeableness"],
    "adoration": ["Agreeableness"],
    "aestheticAppreciation": ["Openness"],
    "amusement": ["Extraversion"],
    "anger": ["Neuroticism"],
    "annoyance": ["Neuroticism"],
    "anxiety": ["Neuroticism"],
    "awe": ["Openness"],
    "awkwardness": ["Neuroticism"],
    "boredom": ["Low Openness", "Low Conscientiousness"],
    "calmness": ["Low Neuroticism"],
    "concentration": ["Conscientiousness"],
    "contemplation": ["Openness"],
    "confusion": ["Neuroticism"],
    "contempt": ["Low Agreeableness"],
    "contentment": ["Agreeableness", "Low Neuroticism"],
    "craving": ["Low Conscientiousness"],
    "determination": ["Conscientiousness"],
    "disappointment": ["Neuroticism"],
    "disapproval": ["Low Agreeableness"],
    "disgust": ["Low Agreeableness"],
    "distress": ["Neuroticism"],
    "doubt": ["Neuroticism"],
    "ecstasy": ["Extraversion"],
    "embarrassment": ["Neuroticism"],
    "empathicPain": ["Agreeableness"],
    "enthusiasm": ["Extraversion"],
    "entrancement": ["Openness"],
    "envy": ["Neuroticism"],
    "excitement": ["Extraversion"],
    "fear": ["Neuroticism"],
    "gratitude": ["Agreeableness"],
    "guilt": ["Neuroticism"],
    "horror": ["Neuroticism"],
    "interest": ["Openness"],
    "joy": ["Extraversion"],
    "love": ["Agreeableness", "Extraversion"],
    "neutral": [],
    "nostalgia": ["Openness"],
    "pain": ["Neuroticism"],
    "pride": ["Extraversion"],
    "realization": ["Openness"],
    "relief": ["Low Neuroticism"],
    "romance": ["Agreeableness", "Extraversion"],
    "sadness": ["Neuroticism"],
    "sarcasm": ["Low Agreeableness"],
    "satisfaction": ["Conscientiousness", "Low Neuroticism"],
    "sexualDesire": ["Extraversion"],
    "shame": ["Neuroticism"],
    "surprise": ["Openness"],
    "surpriseNegative": ["Neuroticism"],
    "surprisePositive": ["Openness", "Extraversion"],
    "sympathy": ["Agreeableness"],
    "tiredness": ["Neuroticism"],
    "triumph": ["Extraversion", "Conscientiousness"]
  };
  