// app/layout.js

import localFont from "next/font/local";
import "./globals.css";
import FloatingVoiceButton from "@/component/floatingButton";
import Providers from "@/component/providers"; // Adjust the path as necessary

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ErrorBoundary from "@/component/ErrorBoundary";
import { AuthProvider } from "@/context/useAuth";

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <Providers>
            <ErrorBoundary>
              {children}
              <FloatingVoiceButton />
            </ErrorBoundary>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
